# Generated by Django 3.2.18 on 2023-03-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactt',
        ),
    ]
